version: '3'

services:
  angular:
    build:
      context: ./frontend
      dockerfile: angular.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app 

  php:
    build:
      context: ./backend
      dockerfile: php.Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: blagoevgerad
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "8082:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8083:80"
    depends_on:
      - db
